apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: sowrabh-test-ns
  labels:
    app: order
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  selector:
      matchLabels:
        app: order-microservice
  template:
    metadata:
      labels:
        app: order-microservice
    spec:
      containers:
        - name: order-container
          image: kubectlandchill/sales-order-service:v1.0.0
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-config