apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: sowrabh-test-ns
  labels:
    app: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306